# Generated by Django 4.1.5 on 2023-01-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0002_structures_description_structures_pool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.TextField(null=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.structures')),
            ],
        ),
    ]
