# Generated by Django 4.1.5 on 2023-01-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structures',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='structures',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structures',
            name='restaurants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structures',
            name='spa',
            field=models.BooleanField(default=False),
        ),
    ]
